# This is your Editor pane.
apiVersion: v1
kind: Service
metadata:
  name: helminiak-svc
  labels:
    app: helminiak
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
  selector:
    app: helminiak